### ISSUE TITLE
can be used on android 6.0?

### ISSUE THREAD

**Issue by eebssk1** [pylerSM/XInstaller#39]
It can't work on CM13.
The device can boot.(good)
But after I enabled it,"Error parsing package" always shows when i install >new< apps.(what??)
So does it support ANDROID 6.0.1?
@pylerSM

**Comment by easyaspi314** [comment]
Since overlay apps can send touches or block touches, for security reasons,
they block you from installing an APK if there is an overlay. A rogue app
could in theory, pop up the package installer with a virus and press
Install without allowing the user to stop it.

Swipe down and tap on Pixel Filter to temporarily fix it. Then install the
app, and re-enable it.
